#ifndef C_TEST_READER_H
#define C_TEST_READER_H

/* Generated by flatcc 0.5.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct Foo_table *Foo_table_t;
typedef const flatbuffers_uoffset_t *Foo_vec_t;
typedef flatbuffers_uoffset_t *Foo_mutable_vec_t;
typedef const struct Bar_table *Bar_table_t;
typedef const flatbuffers_uoffset_t *Bar_vec_t;
typedef flatbuffers_uoffset_t *Bar_mutable_vec_t;
#ifndef Foo_identifier
#define Foo_identifier flatbuffers_identifier
#endif
#define Foo_type_hash ((flatbuffers_thash_t)0xc7e1677)
#define Foo_type_identifier "\x77\x16\x7e\x0c"
#ifndef Bar_identifier
#define Bar_identifier flatbuffers_identifier
#endif
#define Bar_type_hash ((flatbuffers_thash_t)0xdbbc7dba)
#define Bar_type_identifier "\xba\x7d\xbc\xdb"



struct Foo_table { uint8_t unused__; };

static inline size_t Foo_vec_len(Foo_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Foo_table_t Foo_vec_at(Foo_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Foo_table_t, vec, i, 0)
__flatbuffers_table_as_root(Foo)

__flatbuffers_define_scalar_field(0, Foo, id, flatbuffers_uint64, uint64_t, UINT64_C(0))
__flatbuffers_define_string_field(1, Foo, text, 0)

struct Bar_table { uint8_t unused__; };

static inline size_t Bar_vec_len(Bar_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Bar_table_t Bar_vec_at(Bar_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Bar_table_t, vec, i, 0)
__flatbuffers_table_as_root(Bar)

__flatbuffers_define_scalar_field(0, Bar, id, flatbuffers_uint64, uint64_t, UINT64_C(0))
__flatbuffers_define_string_field(1, Bar, text, 0)
__flatbuffers_define_scalar_field(2, Bar, fooId, flatbuffers_uint64, uint64_t, UINT64_C(0))

#include "flatcc/flatcc_epilogue.h"
#endif /* C_TEST_READER_H */
